services:
  keycloak:
    container_name: keycloak
    image: quay.io/keycloak/keycloak:25.0.1
    env_file:
      - path:  ./.env
    environment:
      KEYCLOAK_ADMIN: ${KEYCLOAK_ADMIN}
      KEYCLOAK_ADMIN_PASSWORD: ${KEYCLOAK_ADMIN_PASSWORD}
    ports:
      - "8080:8080"
    volumes:
    - ./keycloak:/opt/keycloak/data/import
    command: ["start-dev", "--import-realm"]
