// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package database

type Session struct {
	ID           string
	Userid       string
	Accesstoken  string
	Refreshtoken string
	Expiry       int64
	Tokentype    string
}

type ToDoItem struct {
	ID          string
	Name        string
	Description string
}

type User struct {
	ID         string
	Username   string
	Email      string
	Firstname  string
	Lastname   string
	Rawidtoken string
}
