// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: session_queries.sql

package database

import (
	"context"
)

const deleteSession = `-- name: DeleteSession :exec
DELETE FROM Sessions
WHERE Id = ?
`

func (q *Queries) DeleteSession(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, deleteSession, id)
	return err
}

const getSession = `-- name: GetSession :one
SELECT id, userid, accesstoken, refreshtoken, expiry, tokentype FROM Sessions
WHERE Id = ?
LIMIT 1
`

func (q *Queries) GetSession(ctx context.Context, id string) (Session, error) {
	row := q.db.QueryRowContext(ctx, getSession, id)
	var i Session
	err := row.Scan(
		&i.ID,
		&i.Userid,
		&i.Accesstoken,
		&i.Refreshtoken,
		&i.Expiry,
		&i.Tokentype,
	)
	return i, err
}

const insertSession = `-- name: InsertSession :one
INSERT INTO Sessions (
  Id, UserId, AccessToken, RefreshToken, Expiry, TokenType
) VALUES (
  ?, ?, ?, ?, ?, ?
)
RETURNING id, userid, accesstoken, refreshtoken, expiry, tokentype
`

type InsertSessionParams struct {
	ID           string
	Userid       string
	Accesstoken  string
	Refreshtoken string
	Expiry       int64
	Tokentype    string
}

func (q *Queries) InsertSession(ctx context.Context, arg InsertSessionParams) (Session, error) {
	row := q.db.QueryRowContext(ctx, insertSession,
		arg.ID,
		arg.Userid,
		arg.Accesstoken,
		arg.Refreshtoken,
		arg.Expiry,
		arg.Tokentype,
	)
	var i Session
	err := row.Scan(
		&i.ID,
		&i.Userid,
		&i.Accesstoken,
		&i.Refreshtoken,
		&i.Expiry,
		&i.Tokentype,
	)
	return i, err
}

const updateSession = `-- name: UpdateSession :exec
UPDATE Sessions
SET 
  AccessToken = ?,
  RefreshToken = ?,
  Expiry = ?,
  TokenType = ?
WHERE Id = ?
AND UserId = ?
`

type UpdateSessionParams struct {
	Accesstoken  string
	Refreshtoken string
	Expiry       int64
	Tokentype    string
	ID           string
	Userid       string
}

func (q *Queries) UpdateSession(ctx context.Context, arg UpdateSessionParams) error {
	_, err := q.db.ExecContext(ctx, updateSession,
		arg.Accesstoken,
		arg.Refreshtoken,
		arg.Expiry,
		arg.Tokentype,
		arg.ID,
		arg.Userid,
	)
	return err
}
