// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: todoitem_queries.sql

package database

import (
	"context"
)

const deleteToDoItem = `-- name: DeleteToDoItem :exec
DELETE FROM ToDoItems
WHERE Id = ?
`

func (q *Queries) DeleteToDoItem(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, deleteToDoItem, id)
	return err
}

const getToDoItem = `-- name: GetToDoItem :one
SELECT id, name, description FROM ToDoItems
WHERE Id = ? LIMIT 1
`

func (q *Queries) GetToDoItem(ctx context.Context, id string) (ToDoItem, error) {
	row := q.db.QueryRowContext(ctx, getToDoItem, id)
	var i ToDoItem
	err := row.Scan(&i.ID, &i.Name, &i.Description)
	return i, err
}

const insertToDoItem = `-- name: InsertToDoItem :one
INSERT INTO ToDoItems (
  Id, Name, Description
) VALUES (
  ?, ?, ?
)
RETURNING id, name, description
`

type InsertToDoItemParams struct {
	ID          string
	Name        string
	Description string
}

func (q *Queries) InsertToDoItem(ctx context.Context, arg InsertToDoItemParams) (ToDoItem, error) {
	row := q.db.QueryRowContext(ctx, insertToDoItem, arg.ID, arg.Name, arg.Description)
	var i ToDoItem
	err := row.Scan(&i.ID, &i.Name, &i.Description)
	return i, err
}

const listToDoItems = `-- name: ListToDoItems :many
SELECT id, name, description FROM ToDoItems
`

func (q *Queries) ListToDoItems(ctx context.Context) ([]ToDoItem, error) {
	rows, err := q.db.QueryContext(ctx, listToDoItems)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ToDoItem
	for rows.Next() {
		var i ToDoItem
		if err := rows.Scan(&i.ID, &i.Name, &i.Description); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateToDoItem = `-- name: UpdateToDoItem :one
UPDATE ToDoItems
SET 
  Name = ?,
  Description = ?
WHERE Id = ?
RETURNING id, name, description
`

type UpdateToDoItemParams struct {
	Name        string
	Description string
	ID          string
}

func (q *Queries) UpdateToDoItem(ctx context.Context, arg UpdateToDoItemParams) (ToDoItem, error) {
	row := q.db.QueryRowContext(ctx, updateToDoItem, arg.Name, arg.Description, arg.ID)
	var i ToDoItem
	err := row.Scan(&i.ID, &i.Name, &i.Description)
	return i, err
}
