// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: user_queries.sql

package database

import (
	"context"
)

const deleteUser = `-- name: DeleteUser :exec
DELETE FROM Users
WHERE Id = ?
`

func (q *Queries) DeleteUser(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, deleteUser, id)
	return err
}

const getUser = `-- name: GetUser :one
SELECT id, username, email, firstname, lastname, rawidtoken FROM Users
WHERE Id = ? LIMIT 1
`

func (q *Queries) GetUser(ctx context.Context, id string) (User, error) {
	row := q.db.QueryRowContext(ctx, getUser, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Email,
		&i.Firstname,
		&i.Lastname,
		&i.Rawidtoken,
	)
	return i, err
}

const insertUser = `-- name: InsertUser :one
INSERT INTO Users (
  Id, Username, Email, FirstName, LastName, RawIdToken
) VALUES (
  ?, ?, ?, ?, ?, ?
)
RETURNING id, username, email, firstname, lastname, rawidtoken
`

type InsertUserParams struct {
	ID         string
	Username   string
	Email      string
	Firstname  string
	Lastname   string
	Rawidtoken string
}

func (q *Queries) InsertUser(ctx context.Context, arg InsertUserParams) (User, error) {
	row := q.db.QueryRowContext(ctx, insertUser,
		arg.ID,
		arg.Username,
		arg.Email,
		arg.Firstname,
		arg.Lastname,
		arg.Rawidtoken,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Email,
		&i.Firstname,
		&i.Lastname,
		&i.Rawidtoken,
	)
	return i, err
}

const listUsers = `-- name: ListUsers :many
SELECT id, username, email, firstname, lastname, rawidtoken FROM Users
ORDER BY Email
`

func (q *Queries) ListUsers(ctx context.Context) ([]User, error) {
	rows, err := q.db.QueryContext(ctx, listUsers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []User
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.ID,
			&i.Username,
			&i.Email,
			&i.Firstname,
			&i.Lastname,
			&i.Rawidtoken,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateUser = `-- name: UpdateUser :exec
UPDATE Users
SET 
  Username = ?,
  Email = ?,
  FirstName = ?,
  LastName = ?,
  RawIdToken = ?
WHERE Id = ?
`

type UpdateUserParams struct {
	Username   string
	Email      string
	Firstname  string
	Lastname   string
	Rawidtoken string
	ID         string
}

func (q *Queries) UpdateUser(ctx context.Context, arg UpdateUserParams) error {
	_, err := q.db.ExecContext(ctx, updateUser,
		arg.Username,
		arg.Email,
		arg.Firstname,
		arg.Lastname,
		arg.Rawidtoken,
		arg.ID,
	)
	return err
}
